version: "3.8"

services:
  client:
    build:
      context: client
    ports:
      - 8080:80
    depends_on:
      - server
    
  server:
    build:
      context: server
    environment:
      - TYPEORM_HOST=db
      - TYPEORM_USERNAME=pguser
      - TYPEORM_PASSWORD=pguser
      - TYPEORM_DATABASE=pgdb
      - TYPEORM_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=redispass
      - PORT=3030
    volumes:
      - /app/node_modules
      - ./server:/app
    depends_on:
      - db
      - redis
    ports:
      - 3030:3030
    restart: always

  db:
    image: postgres:12
    environment:
      - POSTGRES_USER=pguser
      - POSTGRES_PASSWORD=pguser
      - POSTGRES_DB=pgdb
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data

  redis:
    image: redis:5
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    command: ["redis-server", "/usr/local/etc/redis/redis.conf"]
    
volumes:
  pg_data: