apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cll-demo.server-name" . }}
  labels:
    {{- include "cll-demo.labels" . | nindent 4 }}
data:
  TYPEORM_DATABASE: {{ .Values.server.config.TYPEORM_DATABASE }}
  TYPEORM_PORT: {{ .Values.server.config.TYPEORM_PORT | quote }}
  REDIS_PORT: {{ .Values.server.config.REDIS_PORT | quote }}
  PORT: {{ .Values.server.port | quote }}
  NODE_ENV: {{ .Values.server.config.NODE_ENV }}
  