{{- if eq .Values.ephemeral false }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "cll-demo.server-name" . }}
  labels:
    {{- include "cll-demo.labels" . | nindent 4 }}
spec:
  backendType: secretsManager
  data:
  - key:  {{ .Values.server.secrets.db_user.key }}
    name: {{ .Values.server.secrets.db_user.name }}
    property: {{ .Values.server.secrets.db_user.property }}
    version: {{ .Values.server.secrets.db_user.version }}
  - key:  {{ .Values.server.secrets.db_pass.key }}
    name: {{ .Values.server.secrets.db_pass.name }}
    property: {{ .Values.server.secrets.db_pass.property }}
    version: {{ .Values.server.secrets.db_pass.version }}
  - key:  {{ .Values.server.secrets.db_host.key }}
    name: {{ .Values.server.secrets.db_host.name }}
    property: {{ .Values.server.secrets.db_host.property }}
    version: {{ .Values.server.secrets.db_host.version }}
  - key:  {{ .Values.server.secrets.redis_host.key }}
    name: {{ .Values.server.secrets.redis_host.name }}
    property: {{ .Values.server.secrets.redis_host.property }}
    version: {{ .Values.server.secrets.redis_host.version }}
{{ end }}
