{{- if eq .Values.ephemeral true }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "cll-demo.server-name" . }}
  labels:
    {{- include "cll-demo.labels" . | nindent 4 }}
type: Opaque
data:
  TYPEORM_HOST: {{ .Values.server.secrets.TYPEORM_HOST | b64enc }}
  TYPEORM_USERNAME: {{ .Values.server.secrets.TYPEORM_USERNAME | b64enc }}
  TYPEORM_PASSWORD: {{ .Values.server.secrets.TYPEORM_PASSWORD | b64enc }}
  REDIS_HOST: {{ .Values.server.secrets.REDIS_HOST | b64enc }}
{{ end }}
