apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.server.name }}
  labels:
    {{- include "cll-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "cll-demo.server-name" . }}
  ports:
    - port: {{ .Values.server.port }}
      targetPort: {{ .Values.server.port }}
  