apiVersion: v1
kind: Service
metadata:
  name: {{ include "cll-demo.client-name" . }}-lb
  labels:
    {{- include "cll-demo.labels" . | nindent 4 }}
spec:
  selector:
    app: {{ include "cll-demo.client-name" . }}
  ports:
    - port: {{ .Values.client.port }}
      targetPort: {{ .Values.client.port }}
  type: LoadBalancer
