{{- if .Values.postgres.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: postgresql
spec:
  ports:
  - port: {{ .Values.postgres.port }}
    targetPort: {{ .Values.postgres.port }}
    name: postgresql
  selector:
    app: postgresql
{{ end }}
